name: issue-comment-workflow
on: issue_comment

jobs: 
    pr-comment: 
        if: ${{ git.hub.event.issue.pull_request }}
        runs-on: ubuntu-latest 
        steps: 
        - name: pr comment 
          run: echo ${{ git.hub.event.issue.pull_request }}

    issue-comment: 
        if: ${{ !git.hub.event.issue.pull_request }}
        runs-on: ubuntu-latest 
        steps: 
        - name: issue comment 
          run: echo ${{ git.hub.event.issue.pull_request }}
